# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO
ARCHIVED = NO

SRCDIR = ../src/
CFLAGS = -Wall -Wextra -Oz -DCE
CXXFLAGS = -Wall -Wextra -Oz -DCE

# ----------------------------

include $(shell cedev-config --makefile)
